### ISSUE TITLE
Error building with CUDA 12.8

### ISSUE THREAD

**Issue by cslominski** [glotzerlab/hoomd-blue#2018]
### Description

Hi,

I believe HOOMD-blue doesn't build with CUDA 12.8.0 or 12.8.1 due to the absence of the file tex_ref_input_iterator.cuh, which hipCUB  expects. I am also unsure why hipCUB is being used when I have an Nvidia GPU. I am able to compile with CUDA 12.6.3.

Thanks,
Charlie

### Script

```python
Try with CUDA 12.8.1. I can provide more info later.
```

### Output

```shell
In file included from hoomd-blue/hoomd/extern/hipCUB/hipcub/include/hipcub/hipcub.hpp:31,
                 from hoomd-blue/hoomd/CommunicatorGPU.cu:14:
hoomd-blue/hoomd/extern/hipCUB/hipcub/include/hipcub/config.hpp:88:14: fatal error: cub/iterator/tex_ref_input_iterator.cuh: No such file or directory
   88 |     #include <cub/iterator/tex_ref_input_iterator.cuh>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Platform

Linux, GPU

### Installation method

Compiled from source

### HOOMD-blue version

5.1.0

### Python version

3.12.3

**Comment by joaander** [comment]
Yes, HOOMD-blue always uses HIP when `ENABLE_GPU=on`. We don't use tex ref input iterators, does the build succeed if you comment out the offending `#include`?

**Comment by cslominski** [comment]
I'm just confirming that commenting out the file solved the issue for me. I see the full fix is planned for 5.1.1. Thank you.

**Comment by joaander** [comment]
Thanks for confirming!
