### PR TITLE
Support CUDA 12.8

### LINKED ISSUE #2018: Error building with CUDA 12.8
### Description

Hi,

I believe HOOMD-blue doesn't build with CUDA 12.8.0 or 12.8.1 due to the absence of the file tex_ref_input_iterator.cuh, which hipCUB  expects. I am also unsure why hipCUB is being used when I have an Nvidia GPU. I am able to compile with CUDA 12.6.3.

Thanks,
Charlie

### Script

```python
Try with CUDA 12.8.1. I can provide more info later.
```

### Input files

_No response_

### Output

```shell
In file included from hoomd-blue/hoomd/extern/hipCUB/hipcub/include/hipcub/hipcub.hpp:31,
                 from hoomd-blue/hoomd/CommunicatorGPU.cu:14:
hoomd-blue/hoomd/extern/hipCUB/hipcub/include/hipcub/config.hpp:88:14: fatal error: cub/iterator/tex_ref_input_iterator.cuh: No such file or directory
   88 |     #include <cub/iterator/tex_ref_input_iterator.cuh>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected output

_No response_

### Platform

Linux, GPU

### Installation method

Compiled from source

### HOOMD-blue version

5.1.0

### Python version

3.12.3

### PR DESCRIPTION
**Pull request by joaander**
## Description

Make changes needed to compile without errors and warnings using CUDA 12.8.

## Motivation and context

Allow users to compile HOOMD-blue with the latest version of CUDA.

Resolves #2018

## How has this been tested?

HOOMD-blue builds locally with no errors or warnings using CUDA 12.8.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.
- [x] I have summarized these changes in `CHANGELOG.rst` following the established format.

### CODE REVIEW

File: .gitmodules [hunk 1]
```diff
@@ -19,7 +19,7 @@
 	url = https://github.com/mphowardlab/neighbor.git
 [submodule "hoomd/extern/hipper"]
 	path = hoomd/extern/hipper
-	url = https://github.com/mphowardlab/hipper.git
+	url = https://github.com/glotzerlab/hipper.git
```
Comment (mphoward) [inline .gitmodules:22]: @joaander I merged in your PR if you want to keep using my version. If not, we will either need to sync your fork or change back the URL once I make the bigger revisions to hipper. That's on my list to do either later this semester or early summer so that MPCD will support HIP builds

Comment (joaander) [reply .gitmodules:22]: Thanks, I'll sync the fork.

I really need to port the rest of HOOMD over to hipper to avoid further reliance on our really old fork of HIP.

Comment (mphoward) [reply .gitmodules:22]: Yeah, it may be a little labor intensive but having to rely on compiled HIP libraries is frustrating when most users are building CUDA... I'll see how quickly I can get to updating hipper, and I'll let you know what happens when I move MPCD.

I noticed that in rocm 6, the HIP API is much closer to CUDA (e.g., `threadIdx_x` -> `threadIdx.x`, chevrons for kernel launch) so I think the porting might actually be slightly easier to do by global find and replace than it was when we first thought about it.

Comment (joaander) [reply .gitmodules:22]: OK, so I should wait for you to update hipper before I start working on porting `hoomd`, `md`, and `hpmc` to it?

Comment (mphoward) [reply .gitmodules:22]: Yes, I think that will be the best use of your time. I may be able to help you with it too when we get there!

Comment (joaander) [reply .gitmodules:22]: That would be great!
